import 'dart:js_interop';
import 'plan_js.dart';
import 'ingestion_metadata_js.dart';

extension type Event(JSObject _) implements JSObject {
  external JSString? user_id;
  external JSString? device_id;
  external JSNumber? timestamp;
  external JSNumber? event_id;
  external JSNumber? session_id;
  external JSString? insert_id;
  external JSNumber? location_lat;
  external JSNumber? location_lng;
  external JSString? app_version;
  external JSString? version_name;
  external JSString? platform;
  external JSString? os_name;
  external JSString? os_version;
  external JSString? device_brand;
  external JSString? device_manufacturer;
  external JSString? device_model;
  external JSString? carrier;
  external JSString? country;
  external JSString? region;
  external JSString? city;
  external JSString? dma;
  external JSString? idfa;
  external JSString? idfv;
  external JSString? adid;
  external JSString? app_set_id;
  external JSString? android_id;
  external JSString? language;
  external JSString? library;
  external JSString? ip;
  external Plan? plan;
  external IngestionMetadata? ingestion_metadata;
  external JSNumber? revenue;
  external JSNumber? price;
  external JSNumber? quantity;
  external JSString? product_id;
  external JSString? revenue_type;
  external JSObject? extra;
  external JSString? partner_id;
  external JSNumber attempts;
  external JSString event_type;
  external JSObject? event_properties;
  external JSObject? user_properties;
  external JSObject? groups;
  external JSObject? group_properties;
}
