name: Android Bridge Unit Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Flutter packages for example project
        run: cd example && flutter pub get

      - name: Generate local.properties
        run: |
          echo "flutter.sdk=$(which flutter | sed 's|/bin/flutter||')" > example/android/local.properties
          echo "sdk.dir=${ANDROID_HOME}" >> example/android/local.properties
          echo "flutter.buildMode=debug" >> example/android/local.properties

      - name: Unit Test
        run: cd android && ./gradlew testDebugUnitTest