name: Test and Lint

on: [pull_request]

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: 'stable'

      - name: Check Flutter version
        run: flutter --version

      - name: Install packages
        run: flutter pub get

      - name: Linter
        run: flutter analyze

      - name: Test
        run: flutter test
