name: Publish to pub.dev

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Do a dry run to preview instead of a real publish'
        type: choice
        required: true
        default: 'dry-run'
        options:
          - 'dry-run'
          - 'publish'

jobs:
  publish:
    name: Publish

    permissions:
      id-token: write # Required for authentication using OIDC

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # This step sets the GitHub-signed OIDC token for pub.dev
      # Workaround for https://github.com/dart-lang/setup-dart/issues/68
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check Flutter version
        run: flutter --version

      - name: Publish to pub.dev --dry-run
        if: ${{ github.event.inputs.dryRun == 'dry-run' }}
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        if: ${{ github.event.inputs.dryRun == 'publish' }}
        run: flutter pub publish --force
